SELECT 
	C.NOME AS CLIENTE, 
	P.FORMA_PAGAMENTO AS FORMA_PAG,
	'R$ ' || SUM (P.TOTAL) AS TOTAL 
FROM 
	PEDIDOS P
	LEFT JOIN CLIENTES C ON C.ID = P.CLIENTE_ID
	where p.status <> 'Cancelado'
GROUP BY 1, 2